const FLAG_CODES: Record<string, string> = {
  "Россия": "RU",
  "Германия": "DE",
  "Германия ": "DE",
  "Чехия": "CZ",
  "Бельгия": "BE",
  "Литва": "LT",
  "Польша": "PL",
  "Тайланд": "TH",
  "Вьетнам": "VN",
  "Япония": "JP",
  "Мексика": "MX",
  "Нидерланды": "NL",
  "Испания": "ES",
  "Италия": "IT",
  "Ирландия": "IE",
  "Франция": "FR",
  "Великобритания": "GB",
  "Латвия": "LV",
  "Белоруссия": "BY",
  "Китай": "CN",
  "Корея": "KR",
  "Австрия": "AT",
  "Казахстан": "KZ",
  "Армения": "AM",
  "Узбекистан": "UZ",
  "Бразилия": "BR",
  "Канада": "CA",
  "Дания": "DK",
  "Шотландия": "GB",
  "Эстония": "EE",
  "Малайзия": "MY",
  "Тайвань": "TW",
  "США": "US",
};

export function getFlag(country: string): string {
  const code = FLAG_CODES[country] || FLAG_CODES[country.trim()];
  return code ? `/flags/${code}.svg` : "/flags/GB.svg";
}
